Fix import/local conflict in typings (#3801)
It fixes this Typescript error:
```
error TS2440: Import declaration conflicts with local declaration of 'Animated'.
```